
public enum FaseisAitisis {
	PROETOIMASIA,
	ELEGXOS,
	PROTOKOLLISI,
	APORRIPSH,
	ELEGXOS_SYMFERONTWN,
	ORISMOS_EISIGITI,
	EISIGISH,
	PSHFOFORIA,
	APOFASH,
	ENHMERWSH_EREYNHTH,
	ENHMERWSH_GIA_VELTIWSEIS,
	ENHMERWSH_GIA_APODOXH
}
