---
title: "Εργασία 8"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{DejaVuSerif}
lang: el
date: "2024-04-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Διερεύνηση του συνόλου δεδομένων

```{r}
library(caTools)
library(readr)
framingham <- read_csv("F:/Μαθήματα_Στέργιος/Επιχειρηματική_Αναλυτική/Exercises/Exercise_006/framingham.csv",show_col_types = FALSE)  
set.seed(25)
split <- sample.split(framingham$TenYearCHD,SplitRatio=0.65)
train <- subset(framingham,split==TRUE)
test <- subset(framingham,split==FALSE)
summary(framingham)
```

## Δημιουργία μοντέλου λογιστικής παλινδρόμησης και μονέλου CART

Μοντέλο λογιστικής παλινδρόμησης:

```{r}
framinghamLog <- glm(TenYearCHD ~ age + education + cigsPerDay + totChol + sysBP + diaBP + BMI + heartRate + glucose, data=framingham, family=binomial)
summary(framinghamLog)
```


Μοντέλο CART:

```{r}
library(rpart)
library(rpart.plot)
FraminghamTree <- rpart(TenYearCHD ~  age + education + cigsPerDay + totChol + sysBP + diaBP + BMI + heartRate + glucose, data = train, method = "class", minbucket = 1)
prp(FraminghamTree)
summary(FraminghamTree)
```
